server:
  port: 8761
  
spring: 
  application:
     name : eureka-discovery-server
     
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka : false
    fetch-registry : false       