server:
  port: 8081
  
logging:
  level:
    org:
      springframework : debug
  file:
    name: C:/Manjiri/SpringbootConfiguration/logs/FuelGrade/FuelGrade.log
    
spring: 
  application:
     name : fuel-grade-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/FuelStationDatabase
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka : true
    fetch-registry : true
    
# enables Spring Boot Actuator end points
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
resilience4j:
  circuitbreaker:
    configs: 
      shared:
        register-health-indicator: true 
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 40
        slow-call-rate-threshold: 40
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 10s
        wait-duration-in-open-state: 10s
        slow-call-duration-threshold: 2s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      example:
        base-config: shared
                   
      